name: IzmirEshot
options:
  bundleIdPrefix: com.eshot.app
  deploymentTarget:
    iOS: "16.0"
targets:
  IzmirEshot:
    type: application
    platform: iOS
    sources: [IzmirEshot]
    info:
      path: IzmirEshot/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      CODE_SIGNING_ALLOWED: NO
      PRODUCT_BUNDLE_IDENTIFIER: com.eshot.app.IzmirEshot
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_IDENTITY: ""
  
  IzmirEshotTests:
    type: bundle.unit-test
    platform: iOS
    sources: [IzmirEshotTests]
    dependencies:
      - target: IzmirEshot
